{{ if .Values.propagationPolicies.create }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: network-test-config
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      name: network-test-config
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
{{- end }}