{{ if .Values.propagationPolicies.create }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: {{ include "network-test.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ServiceAccount
      name: {{ include "network-test.serviceAccountName" . }}
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
{{- end }}
