---
repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: |
          bash -c 'source .venv/bin/activate &&
          for dir in clusters/*/ansible/; do (cd "$dir" &&
          echo "Running ansible-lint in $dir" &&
          ansible-lint ) || exit 1; done'
        language: system
        pass_filenames: false
        always_run: true


  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.28  # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: helmlint
