# group_vars/all.yml
---
# Cluster configuration
cluster_name: microk8s-cluster
microk8s_channel: 1.30stable

# Network configuration
control_plane_ip: 192.168.1.100  # Virtual IP for HA control plane
pod_network_cidr: 10.244.0.0/16
service_cidr: 10.96.0.0/12

# MicroK8s addons to enable
microk8s_addons:
  - dns
  - storage
  - ingress
  - metallb:192.168.1.100-192.168.1.110
  - dashboard
  - metrics-server

# SSH configuration
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_become: yes

# System requirements
system_memory_minimum_mb: 4096
system_cpu_minimum: 2