---
- name: Common Setup
  hosts: all
  become: true
  roles:
    - role: common

- name: Setup K3S clusters
  hosts: all
  become: true
  roles:
    - role: k3s

- name: Setup Karmada Control Plane and Member Clusters
  hosts: all
  become: true
  roles:
    - role: karmada
