---
# - name: Cluster prep
#   hosts: all
#   become: true
#   roles:
#     - role: common

- name: Setup K3S clusters
  hosts: all
  become: true
  roles:
    - role: k3s_server

# - name: Setup Karmada Control Plane
#   hosts: control
#   become: true
#   roles:
#     - role: karmada_host
