---
- name: Ensure playbook is running on Ubuntu
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Ubuntu"
    msg: "This playbook is only designed for Ubuntu systems"

- name: Enforce minimum Ansible version
  ansible.builtin.assert:
    that:
      - ansible_version.full is version('2.15', '>=')
    msg: Minimum ansible-core version required is 2.15

- name: Setup hostnames
  ansible.builtin.include_tasks: hostname.yml

- name: Setup system
  ansible.builtin.include_tasks: system.yml

- name: Setup network
  ansible.builtin.include_tasks: network.yml

- name: Setup k3s pre-reqs
  ansible.builtin.include_tasks: k3s.yml
