{{ if and .Values.grafana.deploy .Values.grafana.propagationPolicies.create }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: grafana-dashboards
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      name: grafana-dashboards
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: grafana-config-dashboards
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      name: monitoring-grafana-config-dashboards
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: grafana-cm
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ConfigMap
      name: monitoring-grafana
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: grafana-secret
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      name: monitoring-grafana
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: grafana-deploy
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: monitoring-grafana
  placement:
    clusterAffinity:
      clusterNames: []
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: grafana-sa
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ServiceAccount
      name: monitoring-grafana
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: monitoring-grafana-svc
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: monitoring-grafana
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy

metadata:
  name: grafana-cr
  namespace: {{ $.Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: monitoring-grafana-clusterrole
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: monitoring-grafana-clusterrolebinding-clusterrolebinding
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
{{- end }}