{{ if .Values.prometheus.propagationPolicies.create }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: kube-state-metrics-deploy
  namespace: {{ .Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: monitoring-kube-state-metrics
  placement:
    clusterAffinity:
      clusterNames: []
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: kube-state-metrics-sa
  namespace: {{ .Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ServiceAccount
      name: monitoring-kube-state-metrics
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: kube-state-metrics-svc
  namespace: {{ .Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: monitoring-kube-state-metrics
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
{{ end }}