{{ if .Values.prometheus.propagationPolicies.create }}
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: prometheus-node-exporter-ds
  namespace: {{ .Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: monitoring-prometheus-node-exporter
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: prometheus-node-exporter-sa
  namespace: {{ .Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: ServiceAccount
      name: monitoring-prometheus-node-exporter
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy

metadata:
  name: node-exporter-svc
  namespace: {{ .Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Service
      name: monitoring-prometheus-node-exporter
  placement:
    clusterAffinity:
      clusterNames: []  # Empty array means propagate to all registered clusters
    replicaScheduling:
      replicaSchedulingType: Duplicated  # Alternative: Duplicated
{{- end }}