apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: "{{ .Release.namespace }}"
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      {{- if (and (eq .Values.prometheus.service.type "NodePort") (not (empty .Values.prometheus.service.nodePort))) }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
      {{- end }}
      nodePort: {{ .Values.prometheus.service.nodePort}}
  type: {{ .Values.prometheus.service.type}}