{{- if .Values.prometheus.federation.enabled }}
# Federation jobs configuration
{{- range $cluster := .Values.prometheus.federation.clusters }}
- job_name: 'federate-{{ $cluster.name }}'
  scrape_interval: {{ $.Values.prometheus.federation.scrapeInterval | default "15s" }}
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      {{- range $.Values.prometheus.federation.matchSelectors }}
      - '{{ . }}'
      {{- end }}
  {{- if hasKey $cluster "auth" }}
  {{- if $cluster.auth.enabled }}
  scheme: {{ $cluster.auth.scheme | default "https" }}
  tls_config:
    ca_file: {{ $cluster.auth.caFile }}
    {{- if $cluster.auth.insecureSkipVerify }}
    insecure_skip_verify: {{ $cluster.auth.insecureSkipVerify }}
    {{- end }}
  authorization:
    credentials_file: {{ $cluster.auth.tokenFile }}
  {{- end }}
  {{- end }}
  static_configs:
    - targets:
      - '{{ $cluster.endpoint }}'
      labels:
        cluster: '{{ $cluster.name }}'
{{- end }}
{{- end }}