---
name: Check Version Update
on:
  pull_request:
    paths:
      - src/**
    branches:
      - main
      - master
jobs:
  check-version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Check if src files changed
        id: src-changes
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^src/" && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Check if pyproject.toml version was updated
        id: version-check
        if: steps.src-changes.outputs.changed == 'true'
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^pyproject.toml"; then
            BASE_VERSION=$(git show ${{ github.event.pull_request.base.sha }}:pyproject.toml | grep -oE 'version\s*=\s*"[0-9]+\.[0-9]+\.[0-9]+"' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            HEAD_VERSION=$(git show ${{ github.event.pull_request.head.sha }}:pyproject.toml | grep -oE 'version\s*=\s*"[0-9]+\.[0-9]+\.[0-9]+"' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            
            echo "Base version: $BASE_VERSION"
            echo "Head version: $HEAD_VERSION"
            
            if [ "$BASE_VERSION" != "$HEAD_VERSION" ]; then
              echo "Version in pyproject.toml was updated from $BASE_VERSION to $HEAD_VERSION"
              echo "updated=true" >> $GITHUB_OUTPUT
            else
              echo "Version in pyproject.toml was not updated"
              echo "updated=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "pyproject.toml was not modified"
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Fail if version was not updated
        if: steps.src-changes.outputs.changed == 'true' && steps.version-check.outputs.updated == 'false'
        run: |-
          echo "::error::Changes detected in src/ directory but version in pyproject.toml was not updated"
          exit 1
